### PR TITLE
feat: Include editor settings

### PR DESCRIPTION
**Pull request by nemchik**
Skipping the PR template again, as this is a small change.

It would be great if the editor settings could be included in the repository so that contributors will be able to use editors in configured with the same settings being used by the maintainers. This is also beneficial for maintainers to keep their settings in sync with each other.

### CODE REVIEW

**Comment by ernscht** [comment]
Thanks for your idea.
But we will not merge this.

There are countless editors and each developer should be allowed to use his settings.
However, for your desired purpose, there is a .editorconfig (https://editorconfig.org/) included. In combination with the linters and prettier this should work cleanly in our experience.

Have you had other experiences?

**Comment by nemchik** [comment]
> Have you had other experiences?

Yes I have actually.

Ignoring the folder isn't causing a specific problem. But including the folders can allow synchronizing workspaces between developers and contributors. A very good example is the `.vscode` folder can include a list of recommended extensions to use when opening this repo as a workspace in vscode. The editor will prompt you to install the recommended extensions, but it's still optional. Workspace specific settings can override user defined settings for the editor, but only when working with the repo opened as a workspace in vscode. For example you could have specific settings for the vscode eslint or prettier extension that will be applied only when opening this repo in vscode. You can also setup interface shortcuts for npm scripts and debugging.

I use vscode as the example, but every editor could have settings. It only makes sense to include the ones used by the devs in the repo. So if you are using vscode your repo specific settings for vscode could be available to contributors.

I also love editorconfig, and I'm glad it's already included.

**Comment by ernscht** [comment]
The functionality of Editor Settings are clear to me. I rather meant if you had problems in using the repo?

If there are problems, we can try to solve them. 
But I don't want to maintain editor settings, the effort doesn't give any added value.

**Comment by nemchik** [comment]
That is fair. I have not had problems using the repo aside from not fully understanding the processes in place for development. In part this is similar to https://github.com/namics/webpack-config-plugins/issues/87

If anything I would be curious what code editor you use, and what extensions you may have installed that make developing in this repo easier (if any).

**Comment by ernscht** [comment]
I agree with you of course, working with this monorepo is not self-explanatory . And we should revise the documentation after the update.

This repo does not require any special settings or extensions.  However, the VS Code basic extensions EditorConfig, ESLint and prettier are certainly helpful.

I mostly work with the JetBrains IDE WebStorm and for smaller projects also with VS Code.

**Pull request closed without merging**
