### PR TITLE
Test on Windows using Travis CI

### PR DESCRIPTION
**Pull request by DanielRuf**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [x] The commit message follows our guidelines: link tbd.
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] tooling / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Use Travis CI for Windows and Linux.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi @jantimon,

can you describe why the PR was closed? Do you not want to test on Windows?

**Comment by DanielRuf** [comment]
Hi @jantimon,

can you describe why the PR was closed? Do you not want to test on Windows using Travis CI?

**Comment by jantimon** [comment]
Hey @DanielRuf I closed this pull request as the pipeline failed and there was no update for 4 month.

**Comment by DanielRuf** [comment]
We could hae triggered a new build.
Some older Travis CI builds had issues with npm. See https://travis-ci.org/namics/webpack-config-plugins/jobs/490564863

I'll open a new PR to test the current setup.

**Comment by jantimon** [comment]
Cool thanks 👍

**Pull request closed without merging**
