### PR TITLE
ci: cache node_modules

### PR DESCRIPTION
**Pull request by DanielRuf**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows our guidelines: link tbd.
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] tooling / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Every build does not use the internal Travis CI cache.

Issue Number: N/A

## What is the new behavior?
Builds will be faster due to the Travis CI cache.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by jantimon** [comment]
Will this cleanup a package before the test runs if we remove it from the package.json?

**Comment by DanielRuf** [comment]
> Will this cleanup a package before the test runs if we remove it from the package.json?

Yes because the node_modules will be different and will have a different checksum which will lead to a new cache archive.

**Comment by jantimon** [comment]
Okay could you please explain a little bit more how that cache works?

**Comment by DanielRuf** [comment]
Mh, not sure but it seems the builds take longer. Not yet sure why.

**Comment by jantimon** [comment]
Closing for now as it did not improve the build

**Comment by jantimon** [comment]
I am not sure just following your findings: 
https://github.com/namics/webpack-config-plugins/pull/28#issuecomment-449397927

**Pull request closed without merging**
