### PR TITLE
ci: test on Windows and Linux

### PR DESCRIPTION
**Pull request by DanielRuf**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows our guidelines: link tbd.
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] tooling / infrastructure changes
[ ] Other... Please describe:
```

## What is the current behavior?

Travis CI does not test on Windows.

Issue Number: N/A

## What is the new behavior?
Travis Ci will run the tests on Windows.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

### CODE REVIEW

**Comment by jantimon** [comment]
The test fails on windows but travis says everything is okay.  
Do you think this can be fixed?

**Comment by DanielRuf** [comment]
> The test fails on windows

Can you link the relevant log line(s)? So far I see succeeding test suites.

**Comment by DanielRuf** [comment]
I guess you mean https://travis-ci.org/namics/webpack-config-plugins/jobs/470973035#L459 and others. But it seems `lerna test` does not exit with the correct exit code.

**Comment by DanielRuf** [comment]
I guess you mean https://travis-ci.org/namics/webpack-config-plugins/jobs/470973035#L459 and others. But it seems lerna does not exit with the correct exit code.

**Comment by jantimon** [comment]
Is there any way we could get the correct exit code from lerna?  
Because otherwise this pull request will not provide a useful feedback.

**Comment by DanielRuf** [comment]
Not sure, I've never used lerna (we just use Yarn workspaces and so on).
I would have to dig a bit deeper and test it on my Windows machine at home.

**Comment by jantimon** [comment]
Cool 👍

**Comment by DanielRuf** [comment]
Seems only https://travis-ci.org/namics/webpack-config-plugins/jobs/470995396#L403 is left.

**Comment by jantimon** [comment]
Closing for now as travis won't show errors if tests fail

**Comment by jantimon** [comment]
I really like your idea but as long as it doesn't guarantee that we detect windows errors this pull request can't be merged.

If you manage to fix the false positives I would love to switch to travis from appveyour

**Pull request closed without merging**
